import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./index.css";
import CustomApp from "./CustomApp.jsx";
import Users, { UsersWithImages } from "./Users.jsx";
import ShapeContainer from "./ShapeContainer.jsx";
import UsersFilter from "./UsersFilter.jsx";
import Chameleon from "./Chameleon.jsx";
import Counter from "./Counter.jsx";
ReactDOM.createRoot(document.getElementById("root")).render(<Counter />);
